### ISSUE TITLE
Systemd on flasher images seems to have a dependency on docker

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#142]
`[    6.512183] systemd[1]: docker.service: Cannot add dependency job, ignoring: Unit docker.service failed to load: No such file or directory.`

**Comment by floion** [comment]
This is because of the dnsmasq.service which has a dependency on docker.service.
This dependency is there so that we are sure that on non-flasher images docker is started before dnsmasq so docker0 interface is created at the time dnsmasq is started in case we want dnsmasq to bind to that interface (not used at the moment.)
The fact that docker.service is not present in the flasher images has no impact because dnsmasq has a Wants on this service and not a Requires so it is not fatal

**Comment by agherzan** [comment]
Understand now the roots of it. Even so, we should avoid this kind of warnings. Can we have a drop in for the flasher?

**Comment by agherzan** [comment]
@floion Do we want dnsmasq to bind to docker0 interface? Do we have a usecase for this?

**Comment by floion** [comment]
@petrosagg had at some point. At this very moment, none that I am aware of. Petros, any thoughts on this for the future?

**Comment by agherzan** [comment]
@petrosagg Any feedback on this?

**Comment by petrosagg** [comment]
We want dnsmasq to bind on `docker0` so that when we run containers without host networking they can reach the local resolver.

This happens because by default dnsmasq binds on the localhost interface of the host network namespace which has the subnet 127.0.0.1/8. A docker container without host networking get's a brand new network namespace with its own dedicated localhost interface with the same subnet, so packets can't be routed to the correct process.
