### ISSUE TITLE
How do I install the touchscreen driver for waveshare display on Resin OS?

### ISSUE THREAD

**Issue by derrickaxel** [resin-os/resinos#177]
I bought this 5" waveshare display for my RPI3 which comes with a CD containing the touchscreen's drivers.the drivers can also be downloaded here http://www.waveshare.com/wiki/5inch_HDMI_LCD. My RPI 3 is running the ResinOS. the display works fine when I added:

max_usb_current=1
hdmi_group=2
hdmi_mode=87
hdmi_cvt 800 480 60 6 0 0 0

to my config.txt file but the touchscreen is not and I am not sure how to install the drivers for it. I sshed to the device and run ./LCD5-show 0 but it did no work. does anybody know how I could make the touchscreen work on the ResinOS? Can I install it the driver with a docker file?

**Comment by agherzan** [comment]
Hello @derrickaxel . From what I see there are no drivers per se. From the pointed archive I get only dtbs, config.txt etc.

Generally everything should be as simple as injecting the DTBs in the boot partition and adding the right configuration to config.txt. The only blocker that I see at this point is cmdline.txt and that is because our hostOS update tool (resinhup) uses that to  switch to the updated rootfs partition after an update (before reboot). On the other hand as long as you only add arguments (and not change current one) you should be sorted with this too.

The X conf files should go in the container (your app) so shouldn't need any changes on host for these.

@petrosagg What do you think about this?

Regards,
Andrei

**Comment by derrickaxel** [comment]
@agherzan thank you for answer.
I will try to inject the DTBs in the boot partition tonight and see where it gets me. I did not understand that part. what do you mean by adding argument? 
"On the other hand as long as you only add arguments (and not change current one) you should be sorted with this too"

Thank you,
Derrick

**Comment by agherzan** [comment]
I referring to the cmdline.txt file. That includes arguments to be passed to kernel.

**Comment by willnewton** [comment]
I'm closing this issue as it seems to be resolved. If you're still experiencing problems please feel free to start a new topic at https://forums.resin.io where we'd be happy to help you with any problems you might be having.
