### ISSUE TITLE
resin-filesystem-expand.service appears to run on every boot, slowing down boot time drastically.

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resinos#219]
On a rpi3 2.0.0-beta10 image, it takes 1 minute 20 seconds from power on until my code is runnning.
When remounted the rootFS and disabled the `resin-filesystem-expand`, now it takes ~37seconds for the same code to be running from power on. 

Looking at the systemd boot chart from https://www.flowdock.com/rest/files/86858/UMAWsrJSv1o4ajt8nTolBA/2X_boot.svg , it looks like the filesystem expand service takes about 31 seconds which seems to fit the above tests 😄

**Comment by agherzan** [comment]
This is due to the fsck that we do at every boot. I think it's a good idea to keep it. This operation tupically takes 20-30 seconds in my tests. @petrosagg What do you think?

**Comment by shaunmulligan** [comment]
I think 30 seconds is unacceptable, it almost doubles the boot time for a rpi3

**Comment by shaunmulligan** [comment]
We have had a bunch of people complain about how slowly resinOS boots and gets their code running

**Comment by tixxdz** [comment]
I couldn't access those logs... fsck on ext4 should be faster, but also strictly speaking since btrfs xfs do not really use fsck, most users these days are used to just disable it... so maybe plug a `tune2fs` command in the middle and set a fair `mount-count` value that may depend on the filesystem size too.. it can also be different if the fs is ext3 or ext4 where ext4 rarely need it...

Not sure if this works since I didn't see the logs, and I'm new to resinos. Thanks!

**Comment by agherzan** [comment]
Hi @tixxdz . We currently not use BTRFS anymore. We switched on ext4 on which we run aufs  for docker needs.

**Comment by tixxdz** [comment]
Hi @agherzan ok. So normally fsck boots faster on ext4 when it is run on the second time, it seems that first run it will construct a list of unused inodes where in the second run it will skip them... so this may speed up things if you have a large number of unused inodes. Otherwise we can tune the parameters on how often fsck is run with tune2fs... 

I'm still trying to get resin os running on my board, not sure if you are using `systemd-fsck` but maybe this will help... To disable `systemd-fsck` on boot pass `fsck.mode=skip` in kernel parameters this will disable `systemd-fsck`, or the old trick to skip a mount point is to set `passno` in `/etc/fstab` to zero ...

IMHO running fsck is always good the default in `systemd-fsck` is `auto` which translates later to the settings of the filesystem... maybe @shaunmulligan you can tune your ext4 fs with tune2fs ... just my two cents.

**Comment by agherzan** [comment]
@shaunmulligan please try to reproduce on 2.0.0-rc1 .

**Comment by floion** [comment]
@agherzan @telphan what is the status of this issue? Is it still reproducible on latest rc?

**Comment by telphan** [comment]
@floion this is no longer reproducible with 2.0.0-rc4. The services take on average 2 seconds to activate.

**Comment by floion** [comment]
Good. @shaunmulligan to test and close if happy with it

**Comment by agherzan** [comment]
@shaunmulligan said he can't reproduce this anymore. Considering it fixed. Feel free to reopen if needed.
