### ISSUE TITLE
Initramfs scripts break when using console=null

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinos#230]
Ref: https://github.com/raspberrypi/linux/issues/1892

Reproducable on 2.0.0-rc3

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_18t5)

**Comment by agherzan** [comment]
To test a temporary solution of having console=tty2 in production builds.

**Comment by willnewton** [comment]
From my tests it looks like when passing console=null devtmpfs creates a /dev/console but opening it returns ENODEV rather than behaving like /dev/null which I had imagined it would. I suspect that the switch_root call is indeed the part that is failing as it does an open on the console device and exits if it fails.

**Comment by willnewton** [comment]
My current feeling is this should be closed as wontfix - console=null being incompatible with Yocto initramfs startup scripts. The issue of switching to tty2 is then part of #244 I believe?

**Comment by agherzan** [comment]
@willnewton console=null is indeed incompatible with yocto initramfs but this doesn't mean that this isn't an issue. It is very common for console=null when no logs are wanted and it is supposed to not break the system. In the meanwhile I found the issue and fixed it. See the connected PR.

**Comment by floion** [comment]
nice find @willnewton
